# Generated by Django 5.2.17 on 2026-09-24 16:48

from django.db import migrations, models

from core.migration_ops import AddIndexOnline, TrigramSearchIndexes


class Migration(migrations.Migration):
    # Indexes on large tables are built CONCURRENTLY on PostgreSQL.
    atomic = False

    dependencies = [
        ("users", "0006_productauditevent"),
    ]

    operations = [
        AddIndexOnline(
            model_name="productauditevent",
            index=models.Index(
                fields=["-created_at", "-id"], name="audit_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="user",
            index=models.Index(
                fields=["first_name", "last_name", "id"], name="user_name_order_idx"
            ),
        ),
        TrigramSearchIndexes([
            ("users", "user", "first_name"),
            ("users", "user", "last_name"),
            ("users", "user", "email"),
            ("users", "user", "username"),
            ("users", "productauditevent", "target_label"),
        ]),
    ]
