# Generated by Django 5.2.17 on 2026-10-10 08:33

from django.db import migrations, models


def mark_individual_plans(apps, schema_editor):
    # Every plan defaults to schools; the seeded individual plan is the only exception.
    Plan = apps.get_model('users', 'Plan')
    Plan.objects.filter(code='individual-counselor').update(workspace_type='individual')


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_s2_dashboard_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="workspace_type",
            field=models.CharField(
                choices=[
                    ("school", "Organization school"),
                    ("individual", "Individual counselor workspace"),
                ],
                default="school",
                help_text="The kind of workspace this plan can be given to.",
                max_length=16,
            ),
        ),
        migrations.RunPython(mark_individual_plans, migrations.RunPython.noop),
    ]
