# Generated by Django 5.2.17 on 2026-10-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_s2_dashboard_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedRefreshSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
