# Generated by Django 5.2.17 on 2026-10-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_plan_workspace_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("started_at", models.DateTimeField()),
                ("duration_seconds", models.FloatField(default=0)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("ok", "Finished"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped: already running"),
                        ],
                        max_length=16,
                    ),
                ),
                ("processed", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["name", "-started_at"], name="job_run_name_started_idx"
                    )
                ],
            },
        ),
    ]
