# Generated by Django 5.2.4 on 2026-07-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_school_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=220)),
                ('activity_type', models.CharField(choices=[('extracurricular', 'Extracurricular'), ('volunteering', 'Volunteering'), ('leadership', 'Leadership'), ('club', 'Club'), ('competition', 'Competition'), ('community', 'Community Service'), ('other', 'Other')], default='extracurricular', max_length=40)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('impact', models.CharField(blank=True, max_length=255)),
                ('hours_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weeks_per_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='admissions.studentprofile')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('issuer', models.CharField(blank=True, max_length=220)),
                ('level', models.CharField(choices=[('school', 'School'), ('regional', 'Regional'), ('national', 'National'), ('international', 'International')], default='school', max_length=30)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='honor_proofs/')),
                ('verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honors', to='admissions.studentprofile')),
            ],
            options={
                'ordering': ['-award_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(max_length=220)),
                ('position', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('supervisor', models.CharField(blank=True, max_length=180)),
                ('verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='admissions.studentprofile')),
            ],
            options={
                'ordering': ['-start_date', 'organization'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField()),
                ('impact', models.CharField(blank=True, max_length=255)),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='admissions.studentprofile')),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommender_name', models.CharField(max_length=180)),
                ('recommender_title', models.CharField(blank=True, max_length=180)),
                ('recommender_email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('drafting', 'Drafting'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='requested', max_length=30)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='recommendation_letters/')),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='admissions.studentprofile')),
            ],
            options={
                'ordering': ['deadline', 'recommender_name'],
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('field', models.CharField(blank=True, max_length=160)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField()),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researches', to='admissions.studentprofile')),
            ],
            options={
                'ordering': ['-start_date', 'title'],
            },
        ),
    ]
