# Generated by Django 5.2.4 on 2026-07-16 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_resourcelibraryitem_storeitem_booking_communitypost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('provider', models.CharField(max_length=180)),
                ('program_type', models.CharField(choices=[('national', 'National'), ('international', 'International')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('delivery_mode', models.CharField(choices=[('onsite', 'On-site'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='onsite', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('eligible_grades', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('fee_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('scholarship_available', models.BooleanField(default=False)),
                ('aid_details', models.CharField(blank=True, max_length=300)),
                ('requirements', models.TextField(blank=True)),
                ('application_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['program_type', 'deadline', 'title'],
            },
        ),
        migrations.AddField(
            model_name='university',
            name='acceptance_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='act_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='act_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='aid_application_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='average_aid_usd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='campus_setting',
            field=models.CharField(blank=True, choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='css_profile_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='degree_type',
            field=models.CharField(choices=[('four_year', '4-year'), ('two_year', '2-year')], default='four_year', max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='fafsa_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='financial_aid_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='institution_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='meets_full_need',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='need_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='net_price_usd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='offers_athletic_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='offers_international_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='offers_merit_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='offers_need_based_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='popular_majors',
            field=models.CharField(blank=True, help_text='Comma-separated majors', max_length=300),
        ),
        migrations.AddField(
            model_name='university',
            name='sat_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='sat_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='student_faculty_ratio',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='students_receiving_aid_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='test_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='tuition_usd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='undergrad_enrollment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('provider', models.CharField(max_length=180)),
                ('scholarship_type', models.CharField(choices=[('merit', 'Merit'), ('need_based', 'Need-based'), ('athletic', 'Athletic'), ('leadership', 'Leadership'), ('research', 'Research'), ('diversity', 'Diversity'), ('full_ride', 'Full ride')], max_length=30)),
                ('funding_level', models.CharField(choices=[('full', 'Full funding'), ('partial', 'Partial funding'), ('fixed', 'Fixed amount')], default='partial', max_length=20)),
                ('scope', models.CharField(choices=[('national', 'National'), ('international', 'International')], default='international', max_length=20)),
                ('amount_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('coverage', models.CharField(blank=True, max_length=300)),
                ('eligible_countries', models.CharField(blank=True, max_length=300)),
                ('eligible_grades', models.CharField(blank=True, max_length=120)),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('min_ielts', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('min_sat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requires_essay', models.BooleanField(default=False)),
                ('requires_recommendation', models.BooleanField(default=False)),
                ('requires_financial_documents', models.BooleanField(default=False)),
                ('requires_transcript', models.BooleanField(default=True)),
                ('requires_cv', models.BooleanField(default=False)),
                ('requires_portfolio', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to='admissions.university')),
            ],
            options={
                'ordering': ['deadline', 'title'],
            },
        ),
    ]
