# Generated by Django 5.2.4 on 2026-07-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_student_workspaces_google_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='google_docs_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='honor',
            name='google_docs_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='google_docs_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='google_docs_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recommendationletter',
            name='google_docs_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='research',
            name='google_docs_url',
            field=models.URLField(blank=True),
        ),
    ]
