# Generated by Django 5.2.4 on 2026-08-10 10:13

import apps.admissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from pathlib import Path
import mimetypes
import shutil


def backfill_document_file_metadata(apps, schema_editor):
    Document = apps.get_model('admissions', 'Document')
    public_root = Path(settings.MEDIA_ROOT).resolve()
    private_root = Path(settings.DOCUMENT_STORAGE_ROOT).resolve()
    for document in Document.objects.exclude(file='').exclude(file__isnull=True).iterator():
        source = (public_root / document.file.name).resolve()
        destination = (private_root / document.file.name).resolve()
        if source.is_relative_to(public_root) and destination.is_relative_to(private_root) and source.exists():
            destination.parent.mkdir(parents=True, exist_ok=True)
            if not destination.exists():
                shutil.copy2(source, destination)
        file_name = Path(document.file.name).name
        try:
            file_size = document.file.size
        except (FileNotFoundError, OSError):
            file_size = 0
        Document.objects.filter(pk=document.pk).update(
            original_file_name=file_name[:255],
            file_content_type=(mimetypes.guess_type(file_name)[0] or 'application/octet-stream')[:120],
            file_size=file_size,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0021_parentstudentlink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="original_file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_student_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.admissions.models.PrivateDocumentStorage(),
                upload_to=apps.admissions.models.student_document_upload_path,
            ),
        ),
        migrations.RunPython(backfill_document_file_metadata, migrations.RunPython.noop),
    ]
