# Generated by Django 5.2.4 on 2026-08-15 07:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0024_private_honor_achievement_evidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="personality_tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated RIASEC codes (R,I,A,S,E,C) used for explainable profile matching",
                max_length=120,
            ),
        ),
        migrations.CreateModel(
            name="PersonalityAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("framework", models.CharField(default="riasec-v1", max_length=40)),
                ("answers", models.JSONField(default=dict)),
                ("scores", models.JSONField(default=dict)),
                ("top_traits", models.JSONField(default=list)),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_assessment",
                        to="admissions.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["student__user__first_name", "student__user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="EssayAIReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("essay_version", models.PositiveIntegerField()),
                ("input_hash", models.CharField(max_length=64)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("mode", models.CharField(default="local-fallback", max_length=30)),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_reviews",
                        to="admissions.essay",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_essay_ai_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("essay", "input_hash"),
                        name="unique_essay_ai_review_input",
                    )
                ],
            },
        ),
    ]
