# Generated by Django 5.2.4 on 2026-08-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admissions",
            "0025_university_personality_tags_personalityassessment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("karakalpakstan", "Republic of Karakalpakstan"),
                    ("andijan", "Andijan"),
                    ("bukhara", "Bukhara"),
                    ("fergana", "Fergana"),
                    ("jizzakh", "Jizzakh"),
                    ("kashkadarya", "Kashkadarya"),
                    ("khorezm", "Khorezm"),
                    ("namangan", "Namangan"),
                    ("navoiy", "Navoiy"),
                    ("samarkand", "Samarkand"),
                    ("sirdaryo", "Sirdaryo"),
                    ("surkhandarya", "Surkhandarya"),
                    ("tashkent_region", "Tashkent Region"),
                    ("tashkent_city", "Tashkent City"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
