# Generated by Django 5.2.4 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0026_challengeattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_google_docs_url',
            field=models.URLField(blank=True),
        ),
    ]
