# Generated by Django 5.2.4 on 2026-09-15 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0027_university_market_program"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResourceLibraryItem",
        ),
    ]
