# Generated by Django 5.2.4 on 2026-09-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0026_challengeattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="application_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="profile_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
