# Generated by Django 5.2.4 on 2026-09-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0028_student_owned_onboarding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="gpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
