# Generated by Django 5.2.4 on 2026-09-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0030_merge_onboarding_and_resource_removal"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapmission",
            name="google_docs_url",
            field=models.URLField(blank=True),
        ),
    ]
