# Generated by Django 5.2.4 on 2026-09-18 14:05

import apps.admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0031_roadmap_mission_google_docs_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="guardian_relation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mother", "Mother"),
                    ("father", "Father"),
                    ("guardian", "Guardian"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.admissions.models.PrivateDocumentStorage(),
                upload_to=apps.admissions.models.student_photo_upload_path,
            ),
        ),
    ]
