# Generated by Django 5.2.4 on 2026-09-19 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0028_delete_resourcelibraryitem"),
        ("admissions", "0032_student_photo_and_guardian"),
    ]

    operations = []
