# Generated by Django 5.2.4 on 2026-09-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0033_merge_main_into_student_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityprogram",
            name="application_open_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunityprogram",
            name="deadline_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunityprogram",
            name="eligible_ages",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="opportunityprogram",
            name="needs_verification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunityprogram",
            name="source_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="opportunityprogram",
            name="source_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="opportunityprogram",
            name="source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="catalog_key",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="currency",
            field=models.CharField(default="UZS", max_length=3),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="deliverables",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="is_sample",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="provider_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="provider_role",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="opportunityprogram",
            name="application_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="opportunityprogram",
            name="delivery_mode",
            field=models.CharField(
                choices=[
                    ("onsite", "On-site"),
                    ("online", "Online"),
                    ("hybrid", "Hybrid"),
                    ("unspecified", "To verify"),
                ],
                default="onsite",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="opportunityprogram",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("national", "National"),
                    ("international", "International"),
                    ("unspecified", "To verify"),
                ],
                max_length=20,
            ),
        ),
    ]
