# Generated by Django 5.2.4 on 2026-09-22 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0035_portal_catalog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommunityPost",
        ),
    ]
