# Generated by Django 5.2.4 on 2026-09-23 15:56

import mimetypes
import shutil
from pathlib import Path

import apps.admissions.models
from django.conf import settings
from django.db import migrations, models


# (model name, file field, name field, content-type field, size field) — one entry
# per model migrating onto the private-storage pipeline in this migration. Mirrors
# 0024_private_honor_achievement_evidence.py's Achievement/Honor backfill, generalized
# because Task and RecommendationLetter don't share a common field-name prefix.
FILE_FIELD_CONFIG = (
    ("Task", "submission_file", "submission_file_name", "submission_file_content_type", "submission_file_size"),
    ("RecommendationLetter", "file", "original_file_name", "file_content_type", "file_size"),
)


def move_existing_files_to_private_storage(apps, schema_editor):
    public_root = Path(settings.MEDIA_ROOT).resolve()
    private_root = Path(settings.DOCUMENT_STORAGE_ROOT).resolve()
    for model_name, file_field, name_field, content_type_field, size_field in FILE_FIELD_CONFIG:
        Model = apps.get_model("admissions", model_name)
        queryset = Model.objects.exclude(**{file_field: ""}).exclude(**{f"{file_field}__isnull": True})
        for record in queryset.iterator():
            relative_name = getattr(record, file_field).name
            source = (public_root / relative_name).resolve()
            destination = (private_root / relative_name).resolve()
            if (
                source.is_relative_to(public_root)
                and destination.is_relative_to(private_root)
                and source.exists()
            ):
                destination.parent.mkdir(parents=True, exist_ok=True)
                if not destination.exists():
                    shutil.copy2(source, destination)
            existing_file = destination if destination.exists() else source
            original_name = Path(relative_name).name
            Model.objects.filter(pk=record.pk).update(**{
                name_field: original_name[:255],
                content_type_field: (mimetypes.guess_type(original_name)[0] or "application/octet-stream")[:120],
                size_field: existing_file.stat().st_size if existing_file.exists() else 0,
            })
            if public_root != private_root and destination.exists() and source.exists():
                source.unlink()


class Migration(migrations.Migration):
    # Stays atomic (unlike apps/users/migrations/0004_counselor_requires_school.py):
    # the backfill above only updates plain name/content-type/size columns, never an
    # FK column, so there are no deferred FK trigger events. The AlterFields below
    # only change a FileField's Python-level storage/upload_to — not part of the SQL
    # column definition — so they emit no ALTER TABLE at all on PostgreSQL.
    dependencies = [
        ("admissions", "0036_remove_community_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationletter",
            name="file_content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="recommendationletter",
            name="file_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recommendationletter",
            name="original_file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="submission_file_content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="task",
            name="submission_file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="submission_file_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RunPython(move_existing_files_to_private_storage, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="recommendationletter",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.admissions.models.PrivateDocumentStorage(),
                upload_to=apps.admissions.models.student_evidence_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="submission_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.admissions.models.PrivateDocumentStorage(),
                upload_to=apps.admissions.models.student_evidence_upload_path,
            ),
        ),
    ]
