# Generated by Django 5.2.4 on 2026-09-24 10:04

import re

import django.db.models.deletion
from django.db import migrations, models

WORD_PATTERN = re.compile(r"\S+")
WHITESPACE_PATTERN = re.compile(r"\s+")
PREVIEW_CHARS = 160


def _preview(text):
    # Frozen copy of essay_lab.doc.make_preview so later code changes can't alter this migration.
    flat = WHITESPACE_PATTERN.sub(" ", text or "").strip()
    if len(flat) <= PREVIEW_CHARS:
        return flat
    cut = flat[:PREVIEW_CHARS]
    if " " in cut[PREVIEW_CHARS // 2:]:
        cut = cut[: cut.rindex(" ")]
    return cut.rstrip() + "\u2026"


def backfill_word_count_and_preview(apps, schema_editor):
    Essay = apps.get_model("admissions", "Essay")
    batch = []
    for essay in Essay.objects.only("id", "content").iterator(chunk_size=500):
        essay.word_count = len(WORD_PATTERN.findall(essay.content or ""))
        essay.preview = _preview(essay.content)
        batch.append(essay)
        if len(batch) >= 500:
            Essay.objects.bulk_update(batch, ["word_count", "preview"])
            batch = []
    if batch:
        Essay.objects.bulk_update(batch, ["word_count", "preview"])


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0037_secure_task_and_recommendation_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="essay",
            name="doc",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="essay",
            name="essay_type",
            field=models.CharField(
                choices=[
                    ("personal_statement", "Personal statement"),
                    ("supplement", "Supplement"),
                    ("scholarship", "Scholarship"),
                    ("free_writing", "Free writing"),
                ],
                default="personal_statement",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="essay",
            name="last_client_save_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="essay",
            name="last_cursor",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="essay",
            name="last_edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="essay",
            name="preview",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="essay",
            name="save_seq",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="essay",
            name="trashed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="essay",
            name="university_name",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="essay",
            name="word_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="essay",
            name="word_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="essay",
            name="prompt",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="EssayCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc", models.JSONField()),
                ("content", models.TextField(blank=True)),
                ("word_count", models.PositiveIntegerField(default=0)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic"),
                            ("depth_check", "Depth check"),
                            ("restore", "Before restore"),
                            ("manual", "Manual"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="admissions.essay",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EssayDepthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("save_seq", models.PositiveIntegerField()),
                ("result", models.JSONField(default=dict)),
                ("model", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depth_checks",
                        to="admissions.essay",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EssayFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="admissions.essayfolder",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_folders",
                        to="admissions.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddField(
            model_name="essay",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="essays",
                to="admissions.essayfolder",
            ),
        ),
        migrations.AddIndex(
            model_name="essay",
            index=models.Index(
                fields=["student", "trashed_at", "-updated_at"],
                name="essay_lab_library_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="essaycheckpoint",
            index=models.Index(
                fields=["essay", "-created_at"], name="essay_checkpoint_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="essaydepthcheck",
            index=models.Index(
                fields=["essay", "-created_at"], name="essay_depth_check_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="essayfolder",
            index=models.Index(
                fields=["student", "parent", "position"], name="essay_folder_order_idx"
            ),
        ),
        migrations.RunPython(backfill_word_count_and_preview, migrations.RunPython.noop),
    ]
