# Generated by Django 5.2.17 on 2026-09-24 10:56

from django.db import migrations, models


def backfill_gpa_scale(apps, schema_editor):
    """Use the scale onboarding stored in application_profile, else infer from the value."""
    StudentProfile = apps.get_model('admissions', 'StudentProfile')
    for profile in StudentProfile.objects.filter(gpa_scale__isnull=True).exclude(gpa__isnull=True).iterator():
        stored = str((profile.application_profile or {}).get('gpa_scale') or '')
        if stored in {'4', '5', '100'}:
            scale = int(stored)
        else:
            value = float(profile.gpa)
            scale = 100 if value > 5 else 5 if value > 4 else 4
        StudentProfile.objects.filter(pk=profile.pk).update(gpa_scale=scale)


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0037_secure_task_and_recommendation_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="gpa_scale",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(4, "4.0"), (5, "5.0"), (100, "100")], null=True
            ),
        ),
        migrations.RunPython(backfill_gpa_scale, migrations.RunPython.noop),
    ]
