# Generated by Django 5.2.17 on 2026-09-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0040_backfill_missing_student_profiles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": [
                    "due_date",
                    models.OrderBy(
                        models.Case(
                            models.When(priority="urgent", then=models.Value(0)),
                            models.When(priority="high", then=models.Value(1)),
                            models.When(priority="medium", then=models.Value(2)),
                            models.When(priority="low", then=models.Value(3)),
                            default=models.Value(4),
                            output_field=models.IntegerField(),
                        )
                    ),
                    "id",
                ]
            },
        ),
    ]
