# Generated by Django 5.2.17 on 2026-09-24 11:43

from django.conf import settings
from django.db import migrations, models


def cancel_duplicate_active_roadmaps(apps, schema_editor):
    """Keep the newest active roadmap per (counselor, kind); cancel older duplicates."""
    CounselorRoadmap = apps.get_model('admissions', 'CounselorRoadmap')
    seen = set()
    for roadmap in CounselorRoadmap.objects.filter(status='active').order_by('-created_at', '-id'):
        key = (roadmap.counselor_id, roadmap.kind)
        if key in seen:
            CounselorRoadmap.objects.filter(pk=roadmap.pk).update(status='cancelled')
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0041_task_priority_ordering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(cancel_duplicate_active_roadmaps, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="counselorroadmap",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("counselor", "kind"),
                name="unique_active_counselor_roadmap_kind",
            ),
        ),
    ]
