# Generated by Django 5.2.17 on 2026-09-24 11:48

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class AddIndexConcurrentlyOnPostgres(AddIndexConcurrently):
    """CREATE INDEX CONCURRENTLY on PostgreSQL (no write lock on big tables
    while instances boot); a plain AddIndex elsewhere (SQLite in development)."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            return super().database_forwards(app_label, schema_editor, from_state, to_state)
        return migrations.AddIndex.database_forwards(self, app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            return super().database_backwards(app_label, schema_editor, from_state, to_state)
        return migrations.AddIndex.database_backwards(self, app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    # CREATE INDEX CONCURRENTLY cannot run inside a transaction.
    atomic = False


    dependencies = [
        ("admissions", "0042_unique_active_counselor_roadmap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrentlyOnPostgres(
            model_name="activitylog",
            index=models.Index(
                fields=["student", "-created_at"], name="activity_student_created_idx"
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="activitylog",
            index=models.Index(
                fields=["actor", "-created_at"], name="activity_actor_created_idx"
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="application",
            index=models.Index(
                fields=["student", "status"], name="app_student_status_idx"
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="document",
            index=models.Index(
                fields=["student", "status"], name="document_student_status_idx"
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="notification",
            index=models.Index(
                fields=["student", "is_read", "-created_at"],
                name="notif_student_read_idx",
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="roadmapmission",
            index=models.Index(
                fields=["student", "status"], name="mission_student_status_idx"
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="task",
            index=models.Index(
                fields=["student", "status"], name="task_student_status_idx"
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="task",
            index=models.Index(
                fields=["student", "due_date"], name="task_student_due_idx"
            ),
        ),
    ]
