# Generated by Django 5.2.4 on 2026-09-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0038_essay_lab"),
        ("admissions", "0043_audit_indexes"),
    ]

    operations = []
