# Generated by Django 5.2.17 on 2026-09-24 16:48

from django.conf import settings
from django.db import migrations, models

from core.migration_ops import AddIndexOnline, TrigramSearchIndexes


class Migration(migrations.Migration):
    # Indexes on large tables are built CONCURRENTLY on PostgreSQL.
    atomic = False

    dependencies = [
        ("admissions", "0044_merge_0038_essay_lab_0043_audit_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexOnline(
            model_name="achievement",
            index=models.Index(
                fields=["-created_at", "-id"], name="achievement_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="activity",
            index=models.Index(
                fields=["-created_at", "-id"], name="activity_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="application",
            index=models.Index(
                fields=["-created_at", "-id"], name="app_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="booking",
            index=models.Index(
                fields=["starts_at", "id"], name="booking_starts_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="document",
            index=models.Index(
                fields=["-created_at", "-id"], name="document_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="essay",
            index=models.Index(
                fields=["-created_at", "-id"], name="essay_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="honor",
            index=models.Index(
                fields=["-created_at", "-id"], name="honor_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="internship",
            index=models.Index(
                fields=["-created_at", "-id"], name="internship_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="meetingnote",
            index=models.Index(
                fields=["-created_at", "-id"], name="meeting_note_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="project",
            index=models.Index(
                fields=["-created_at", "-id"], name="project_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="recommendationletter",
            index=models.Index(
                fields=["-created_at", "-id"], name="recommendation_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="research",
            index=models.Index(
                fields=["-created_at", "-id"], name="research_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="roadmapmission",
            index=models.Index(
                fields=["-created_at", "-id"], name="mission_created_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="supportticket",
            index=models.Index(
                fields=["-updated_at", "-id"], name="support_updated_id_idx"
            ),
        ),
        AddIndexOnline(
            model_name="task",
            index=models.Index(fields=["due_date", "id"], name="task_due_id_idx"),
        ),
        TrigramSearchIndexes([
            ("admissions", "task", "title"),
            ("admissions", "document", "title"),
            ("admissions", "application", "program"),
            ("admissions", "essay", "title"),
            ("admissions", "school", "name"),
            ("admissions", "supportticket", "subject"),
            ("admissions", "roadmapmission", "title"),
        ]),
    ]
