# Generated by Django 5.2.17 on 2026-09-24 16:58

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def mark_admin_created_global_channels(apps, schema_editor):
    """Keep only product-admin channels without a school open to every school.

    Any other public channel without a school becomes visible to its members
    only, which is the fail-closed reading of an ambiguous row.
    """
    MessageChannel = apps.get_model('admissions', 'MessageChannel')
    MessageChannel.objects.filter(
        Q(created_by__is_superuser=True) | Q(created_by__role='admin'),
        school__isnull=True,
        is_public=True,
    ).update(is_global=True)


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0046_safety_sync_student_school"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="messagechannel",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="messagechannel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_global", False),
                    models.Q(("is_public", True), ("school__isnull", True)),
                    _connector="OR",
                ),
                name="global_channel_is_public_without_school",
            ),
        ),
        migrations.RunPython(mark_admin_created_global_channels, migrations.RunPython.noop),
    ]
