# Generated by Django 5.2.17 on 2026-09-24 17:14

from django.db import migrations, models
from django.db.models.functions import Now


def stamp_already_inactive_students(apps, schema_editor):
    StudentProfile = apps.get_model('admissions', 'StudentProfile')
    StudentProfile.objects.filter(user__is_active=False, deactivated_at__isnull=True).update(deactivated_at=Now())


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0047_safety_channel_is_global"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(stamp_already_inactive_students, migrations.RunPython.noop),
    ]
