# Generated by Django 5.2.17 on 2026-09-24 21:01

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


EXAM_KEYS = {
    'ielts_status', 'ielts_score', 'sat_status', 'sat_reading', 'sat_math', 'sat_attempts',
}
STATUSES = {'not_taken', 'planning', 'scheduled', 'taken', 'not_required'}


def section(value):
    try:
        value = int(value)
    except (TypeError, ValueError):
        return None
    return value if 200 <= value <= 800 else None


def move_scores_out_of_json(apps, schema_editor):
    """Copy the test answers onboarding kept in application_profile into columns."""
    StudentProfile = apps.get_model('admissions', 'StudentProfile')
    fields = ['application_profile', 'ielts_status', 'ielts_score', 'ielts_attempts',
              'sat_status', 'sat_reading', 'sat_math', 'sat_attempts']
    rows = (
        StudentProfile.objects.filter(
            Q(ielts_score__isnull=False) | Q(sat_score__isnull=False) | ~Q(application_profile={})
        )
        # Every field bulk_update writes, so it never reloads one per row.
        .only('id', 'sat_score', *fields)
        .order_by('id')
    )
    batch = []
    for profile in rows.iterator(chunk_size=500):
        answers = profile.application_profile if isinstance(profile.application_profile, dict) else {}
        if profile.ielts_score is not None and not 0 <= profile.ielts_score <= 9:
            profile.ielts_score = None
        if profile.ielts_score is not None:
            profile.ielts_status, profile.ielts_attempts = 'taken', 1
        elif answers.get('ielts_status') in STATUSES - {'taken'}:
            profile.ielts_status = answers['ielts_status']
        reading, math = section(answers.get('sat_reading')), section(answers.get('sat_math'))
        if profile.sat_score is not None:
            profile.sat_status = 'taken'
            if reading and math and reading + math == profile.sat_score:
                profile.sat_reading, profile.sat_math = reading, math
            try:
                attempts = int(answers.get('sat_attempts') or 0)
            except (TypeError, ValueError):
                attempts = 0
            profile.sat_attempts = min(max(attempts, 1), 20)
        elif answers.get('sat_status') in STATUSES - {'taken'}:
            profile.sat_status = answers['sat_status']
        profile.application_profile = {key: value for key, value in answers.items() if key not in EXAM_KEYS}
        batch.append(profile)
        if len(batch) >= 500:
            StudentProfile.objects.bulk_update(batch, fields)
            batch = []
    if batch:
        StudentProfile.objects.bulk_update(batch, fields)


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0048_safety_student_deactivated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="ielts_attempts",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="ielts_listening",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="ielts_reading",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="ielts_speaking",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="ielts_status",
            field=models.CharField(
                choices=[
                    ("not_taken", "Not taken yet"),
                    ("planning", "Planning to take"),
                    ("scheduled", "Test date booked"),
                    ("taken", "Score available"),
                    ("not_required", "Not needed"),
                ],
                default="not_taken",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="ielts_test_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="ielts_writing",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sat_attempts",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sat_math",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sat_reading",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sat_status",
            field=models.CharField(
                choices=[
                    ("not_taken", "Not taken yet"),
                    ("planning", "Planning to take"),
                    ("scheduled", "Test date booked"),
                    ("taken", "Score available"),
                    ("not_required", "Not needed"),
                ],
                default="not_taken",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sat_superscore",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sat_superscore_math",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sat_superscore_reading",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sat_test_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(move_scores_out_of_json, migrations.RunPython.noop),
    ]
