# Generated by Django 5.2.17 on 2026-09-24 21:02

import apps.admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0050_center_test_score_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="proof_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.admissions.models.PrivateDocumentStorage(),
                upload_to=apps.admissions.models.student_evidence_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="proof_file_content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="activity",
            name="proof_file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="activity",
            name="proof_file_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
