# Generated by Django 5.2.17 on 2026-09-25 06:27

import re

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


FIRST_TAB_TITLE = "Tab 1"
BATCH = 500
WHITESPACE = re.compile(r"\s")


def move_essays_into_tabs(apps, schema_editor):
    """Every existing essay becomes a document with exactly one tab holding its text.

    Character counts are approximated from the plain text here (list markers
    included); the next autosave recomputes them from the rich doc.
    """
    Essay = apps.get_model("admissions", "Essay")
    EssayTab = apps.get_model("admissions", "EssayTab")
    EssayCheckpoint = apps.get_model("admissions", "EssayCheckpoint")
    EssayDepthCheck = apps.get_model("admissions", "EssayDepthCheck")
    fields = ("id", "doc", "content", "word_count", "save_seq", "last_client_save_id", "last_cursor",
              "last_edited_at", "created_at", "updated_at")
    batch = []
    for essay in Essay.objects.only(*fields).order_by("id").iterator(chunk_size=BATCH):
        text = (essay.content or "").replace("\n", "")
        batch.append(EssayTab(
            essay_id=essay.id, title=FIRST_TAB_TITLE, position=0, doc=essay.doc, content=essay.content or "",
            word_count=essay.word_count, char_count=len(text),
            char_count_no_spaces=len(WHITESPACE.sub("", text)), save_seq=essay.save_seq,
            last_client_save_id=essay.last_client_save_id, last_cursor=essay.last_cursor,
            last_edited_at=essay.last_edited_at,
        ))
        if len(batch) >= BATCH:
            EssayTab.objects.bulk_create(batch)
            batch = []
    if batch:
        EssayTab.objects.bulk_create(batch)
    first_tab = EssayTab.objects.filter(essay_id=OuterRef("essay_id")).order_by("id").values("id")[:1]
    EssayCheckpoint.objects.update(tab_id=Subquery(first_tab))
    EssayDepthCheck.objects.update(tab_id=Subquery(first_tab))


def move_tabs_back_into_essays(apps, schema_editor):
    """Reverse: a one-tab essay gets its rich doc back; with several tabs the
    derived plain text (already in Essay.content) is kept and the doc rebuilt from it."""
    Essay = apps.get_model("admissions", "Essay")
    EssayTab = apps.get_model("admissions", "EssayTab")
    essays = []
    tabs = EssayTab.objects.order_by("essay_id", "parent_id", "position", "id").only(
        "essay_id", "doc", "save_seq", "last_client_save_id", "last_cursor",
    )
    seen = {}
    for tab in tabs.iterator(chunk_size=BATCH):
        seen.setdefault(tab.essay_id, []).append(tab)
    for essay_id, essay_tabs in seen.items():
        first = essay_tabs[0]
        essays.append(Essay(
            id=essay_id, doc=first.doc if len(essay_tabs) == 1 else None,
            save_seq=max(tab.save_seq for tab in essay_tabs) + (0 if len(essay_tabs) == 1 else 1),
            last_client_save_id=first.last_client_save_id if len(essay_tabs) == 1 else "",
            last_cursor=first.last_cursor if len(essay_tabs) == 1 else None,
        ))
    Essay.objects.bulk_update(essays, ["doc", "save_seq", "last_client_save_id", "last_cursor"], batch_size=BATCH)



class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0051_files_activity_proof_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="essay",
            name="page_size",
            field=models.CharField(
                choices=[("a4", "A4"), ("letter", "US Letter")],
                default="a4",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="EssayTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("position", models.PositiveIntegerField(default=0)),
                ("doc", models.JSONField(blank=True, null=True)),
                ("content", models.TextField(blank=True)),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("char_count", models.PositiveIntegerField(default=0)),
                ("char_count_no_spaces", models.PositiveIntegerField(default=0)),
                ("save_seq", models.PositiveIntegerField(default=0)),
                ("last_client_save_id", models.CharField(blank=True, max_length=64)),
                ("last_cursor", models.PositiveIntegerField(blank=True, null=True)),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to="admissions.essay",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="admissions.essaytab",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddField(
            model_name="essaycheckpoint",
            name="tab",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoints",
                to="admissions.essaytab",
            ),
        ),
        migrations.AddField(
            model_name="essaydepthcheck",
            name="tab",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depth_checks",
                to="admissions.essaytab",
            ),
        ),
        migrations.AddIndex(
            model_name="essaycheckpoint",
            index=models.Index(
                fields=["tab", "-created_at"], name="essay_checkpoint_tab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="essaydepthcheck",
            index=models.Index(
                fields=["tab", "-created_at"], name="essay_depth_check_tab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="essaytab",
            index=models.Index(
                fields=["essay", "parent", "position"], name="essay_tab_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="essaytab",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="essay_tab_not_own_parent",
            ),
        ),
        migrations.RunPython(move_essays_into_tabs, move_tabs_back_into_essays),
    ]
