# Generated by Django 5.2.17 on 2026-09-27 09:43

import apps.admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0057_snotif_notification_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmessage",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.admissions.models.PrivateDocumentStorage(),
                upload_to=apps.admissions.models.message_attachment_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="channelmessage",
            name="attachment_content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="channelmessage",
            name="attachment_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="channelmessage",
            name="attachment_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
