# Generated by Django 5.2.17 on 2026-09-27 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0057_snotif_notification_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("task", "Task"),
                    ("document", "Document"),
                    ("deadline", "Deadline"),
                    ("essay", "Essay"),
                    ("meeting", "Meeting"),
                    ("message", "Message"),
                    ("profile_review", "Profile review"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProfileSectionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("personal", "Personal & contact"),
                            ("academics", "Academics"),
                            ("tests", "Test scores"),
                            ("goal", "Study goal & targets"),
                            ("honors", "Honors"),
                            ("activities", "Activities"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_reviewed", "Not reviewed"),
                            ("waiting", "Waiting for review"),
                            ("approved", "Approved"),
                            ("changes_requested", "Needs changes"),
                        ],
                        default="not_reviewed",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_reviews",
                        to="admissions.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["student", "section"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "section"),
                        name="unique_profile_section_review",
                    )
                ],
            },
        ),
    ]
