# Generated by Django 5.2.17 on 2026-09-27 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0059_s2_section_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EssayCommentThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("quote", models.CharField(blank=True, max_length=300)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EssaySuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("delete_text", models.CharField(blank=True, max_length=2000)),
                ("insert_text", models.CharField(blank=True, max_length=2000)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EssayTabEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("edit", "Edit"),
                            ("comment", "Comment"),
                            ("suggest", "Suggestions"),
                            ("decision", "Decisions"),
                        ],
                        default="edit",
                        max_length=12,
                    ),
                ),
                ("save_seq", models.PositiveIntegerField()),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="essay",
            name="collab_seq",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="essay",
            name="counselor_access",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("suggest", "Suggest edits"),
                    ("edit", "Edit"),
                ],
                default="suggest",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="essay",
            name="staff_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="essaycheckpoint",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="essaycheckpoint",
            name="detail",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="essaycheckpoint",
            name="kind",
            field=models.CharField(
                choices=[
                    ("edit", "Edit"),
                    ("comment", "Comment"),
                    ("suggest", "Suggestions"),
                    ("decision", "Decisions"),
                ],
                default="edit",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="essaytab",
            name="last_editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="notif_recipient_read_idx",
            ),
        ),
        migrations.AddField(
            model_name="essaycomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="essaycommentthread",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="essaycommentthread",
            name="essay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_threads",
                to="admissions.essay",
            ),
        ),
        migrations.AddField(
            model_name="essaycommentthread",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="essaycommentthread",
            name="tab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_threads",
                to="admissions.essaytab",
            ),
        ),
        migrations.AddField(
            model_name="essaycomment",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="admissions.essaycommentthread",
            ),
        ),
        migrations.AddField(
            model_name="essaysuggestion",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="essaysuggestion",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="essaysuggestion",
            name="essay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions",
                to="admissions.essay",
            ),
        ),
        migrations.AddField(
            model_name="essaysuggestion",
            name="tab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions",
                to="admissions.essaytab",
            ),
        ),
        migrations.AddField(
            model_name="essaytabedit",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="essaytabedit",
            name="essay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tab_edits",
                to="admissions.essay",
            ),
        ),
        migrations.AddField(
            model_name="essaytabedit",
            name="tab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edits",
                to="admissions.essaytab",
            ),
        ),
        migrations.AddIndex(
            model_name="essaycommentthread",
            index=models.Index(
                fields=["tab", "created_at"], name="essay_thread_tab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="essaysuggestion",
            index=models.Index(
                fields=["tab", "status"], name="essay_suggestion_tab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="essaytabedit",
            index=models.Index(
                fields=["tab", "-created_at"], name="essay_tab_edit_recent_idx"
            ),
        ),
    ]
