# Generated by Django 5.2.17 on 2026-09-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0060_s2_essay_collab"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="counselor_comment",
            field=models.TextField(blank=True),
        ),
    ]
