# Generated by Django 5.2.17 on 2026-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0061_s3_achievement_review_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="previous_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
