# Generated by Django 5.2.17 on 2026-10-09 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def essays_created_by_staff(apps, schema_editor):
    """An essay's first legacy revision names who created it; keep it when that was staff, not the student."""
    Essay = apps.get_model('admissions', 'Essay')
    EssayRevision = apps.get_model('admissions', 'EssayRevision')
    first_author = EssayRevision.objects.filter(essay_id=OuterRef('pk')).order_by('version', 'id').values('created_by_id')[:1]
    (
        Essay.objects.annotate(first_author=Subquery(first_author))
        .exclude(first_author=None)
        .exclude(first_author=models.F('student__user_id'))
        .update(created_by_id=Subquery(first_author))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0064_saved_opportunity_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essay',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='honor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='research',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(essays_created_by_staff, migrations.RunPython.noop),
    ]
