# Generated by Django 5.2.17 on 2026-10-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0068_internship_activity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='intl_cost_usd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
