# Generated by Django 5.2.17 on 2026-10-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0072_university_search_text_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationletter",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recommendationletter",
            name="shared_with_student",
            field=models.BooleanField(default=False),
        ),
    ]
