# Generated by Django 5.2.17 on 2026-10-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0073_recommendation_letter_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationletter",
            name="student_review",
            field=models.CharField(
                blank=True,
                choices=[
                    ("confirmed", "Confirmed"),
                    ("changes_requested", "Changes requested"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recommendationletter",
            name="student_review_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recommendationletter",
            name="student_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
