# Generated by Django 5.2.17 on 2026-10-09 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_replies(apps, schema_editor):
    """Tickets kept only their latest answer until now: it starts each history,
    dated when it was given (auto_now_add would stamp the migration time)."""
    SupportTicket = apps.get_model("admissions", "SupportTicket")
    SupportTicketReply = apps.get_model("admissions", "SupportTicketReply")
    for ticket in SupportTicket.objects.exclude(admin_response="").iterator():
        reply = SupportTicketReply.objects.create(
            ticket_id=ticket.pk, author_id=ticket.responded_by_id, body=ticket.admin_response,
        )
        answered = ticket.responded_at or ticket.updated_at
        SupportTicketReply.objects.filter(pk=reply.pk).update(created_at=answered, updated_at=answered)


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0074_recommendation_letter_student_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicketReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_ticket_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="admissions.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.RunPython(backfill_replies, migrations.RunPython.noop),
    ]
