# Generated by Django 5.2.17 on 2026-10-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0075_support_ticket_reply_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.university'),
        ),
    ]
